MAKEFLAGS += -J2
VERSION=20150704
ONTOLOGY=military
ONTOLOGY_DATE = $(shell m4 -P $(ONTOLOGY).owl | xpath -e '/rdf:RDF/owl:Ontology/dc:date/text()'  2> /dev/null | tr -d "-")
ONTOLOGY_VERSION = $(shell m4 -P $(ONTOLOGY).owl | xpath -e '/rdf:RDF/owl:Ontology/owl:versionInfo/text()' 2> /dev/null)
PREVIOUS_ONTOLOGY = $(shell m4 -P $(ONTOLOGY).owl | xpath -e '/rdf:RDF/owl:Ontology/owl:priorVersion/@rdf:resource'  2> /dev/null | cut -d "\"" -f 2 | rev | cut -d "." -f 2- | cut -d "-" -f 1 |rev)
ONTOLOGY_LONGDATE = $(shell date -d '$(ONTOLOGY_DATE)'  +'%d %B %Y')
all:
$(ONTOLOGY)-template-$(ONTOLOGY_DATE).html: $(ONTOLOGY)-template.html 
	sed "s/PREVIOUS_ONTOLOGY/$(PREVIOUS_ONTOLOGY)/g"  < $(ONTOLOGY)-template.html | sed "s/ONTOLOGY_DATE/$(ONTOLOGY_DATE)/g" |  sed "s/ONTOLOGY_LONGDATE/$(ONTOLOGY_LONGDATE)/g"  | sed "s/ONTOLOGY_VERSION/$(ONTOLOGY_VERSION)/g" > $(ONTOLOGY)-template-$(ONTOLOGY_DATE).html
$(ONTOLOGY)-$(ONTOLOGY_DATE).dot:  $(ONTOLOGY).owl
	rapper -o dot $(ONTOLOGY)-$(ONTOLOGY_DATE).owl > $(ONTOLOGY)-$(ONTOLOGY_DATE).dot
$(ONTOLOGY)-$(ONTOLOGY_DATE).jpg: $(ONTOLOGY)-$(ONTOLOGY_DATE).dot
	dot -o $(ONTOLOGY)-$(ONTOLOGY_DATE).jpg -Tjpg $(ONTOLOGY)-$(ONTOLOGY_DATE).dot
military-raw.html: $(ONTOLOGY)-$(ONTOLOGY_DATE).owl $(ONTOLOGY)-template-$(ONTOLOGY_DATE).html organization.owl military-docs/*.skel military.links military-ranks.links	
	sed -e '/<!-- ontology links -->/r military.links' $(ONTOLOGY)-template-$(ONTOLOGY_DATE).html  > military-skel.html 
#	dot -Tpng -o military.png military.dot
	./create_term_doc.sh military-docs $(ONTOLOGY)-$(ONTOLOGY_DATE).owl
	specgen2.py $(ONTOLOGY)-$(ONTOLOGY_DATE).owl mil military-skel.html military-raw.html -i
#	sed -e '/<!-- ranks are xref here -->/r military-ranks.links' military-raw.html > military-with_rank_xref.html
#	grep "<h2" military-raw.html | sed 's/h2/a/g' | sed 's/<a id=\"/<li><a href=\"#/g' | grep -v "#subtitle" | grep -v "#abstract" | grep -v "#status" | grep -v "#contents" | sed 's/<\/a>/<\/a><\/li>/g' > military.toc
#	grep "<h[1-5] " military-with_rank_xref.html | grep -v "mymw-doctype" | grep -v "title" | grep -v "subtitle" | grep -v "abstract" | grep -v "status" | grep -v "contents" | sed 's/\(<h[1-5] \)\(id=.\(\(.*\)\)"\)/<li><a href="#\3"/g'  |  sed 's/\(<\/h[1-5]\)/\1><\/a><\/li/g'   > military.toc	
#	sed -e '/<!-- document toc goes here -->/r military.toc' military-with_rank_xref.html > military.html 
military.html: military.toc military.links military-ranks.links military-raw.html $(ONTOLOGY)-citations.html
	m4 -P military-raw.html > military.html
	cp $(ONTOLOGY)-$(ONTOLOGY_DATE).owl ~/public_html/military-$(ONTOLOGY_DATE).owl
	cp military.html ~/public_html/.
	cp military.png ~/public_html/. 
deploy: military.html
	cp -f military.owl /var/www/rdf.muninn-project.org/ontologies/military.owl
	cp -f military.owl /var/www/rdf.muninn-project.org/ontologies/military-$(ONTOLOGY_DATE).owl
	cp -f military.html /var/www/rdf.muninn-project.org/ontologies/military.html
	cp -f military.html /var/www/rdf.muninn-project.org/ontologies/military-$(ONTOLOGY_DATE).html
	curl --data "key=4w5y25y265y2y6" --data "query=DELETE+FROM+<http://rdf.muninn-project.org/ontologies/$(ONTOLOGY)>+%0D%0A" "http://rdf.muninn-project.org/sparql"
	sleep 10
	php ~/Store2/muninn_svn/code/load_rdf.php  /var/www/rdf.muninn-project.org/ontologies/$(ONTOLOGY)-$(ONTOLOGY_DATE).owl "http://rdf.muninn-project.org/ontologies/$(ONTOLOGY)"                        
military.toc: military-with_rank_xref.html
	grep "<h[1-5] " military-with_rank_xref.html | grep -v "mymw-doctype" | grep -v "title" | grep -v "subtitle" | grep -v "abstract" | grep -v "status" | grep -v "contents" | sed 's/\(<h[1-5] \)\(id=.\(\(.*\)\)"\)/<li><a href="#\3"/g'  |  sed 's/\(<\/h[1-5]\)/\1><\/a><\/li/g'   > military.toc		
military.links: $(ONTOLOGY)-$(ONTOLOGY_DATE).owl
	./count_linkages.sh $(ONTOLOGY)-$(ONTOLOGY_DATE).owl > military.links
military-ranks.links: $(ONTOLOGY)-$(ONTOLOGY_DATE).owl 	
	./create_rank_xref.sh $(ONTOLOGY)-$(ONTOLOGY_DATE).owl > military-ranks.links
$(ONTOLOGY)-$(ONTOLOGY_DATE).owl: $(ONTOLOGY).owl roman.owl
	m4 -P $(ONTOLOGY).owl > $(ONTOLOGY)-$(ONTOLOGY_DATE).owl
$(ONTOLOGY)-$(ONTOLOGY_DATE).nt: $(ONTOLOGY)-$(ONTOLOGY_DATE).owl
	rapper -o turtle $(ONTOLOGY)-$(ONTOLOGY_DATE).owl > $(ONTOLOGY)-$(ONTOLOGY_DATE).nt
$(ONTOLOGY)-$(ONTOLOGY_DATE).ttl: $(ONTOLOGY)-$(ONTOLOGY_DATE).owl
	rapper -o turtle $(ONTOLOGY)-$(ONTOLOGY_DATE).owl > $(ONTOLOGY)-$(ONTOLOGY_DATE).ttl	
$(ONTOLOGY)-citations.html:     citations.bib
	bibtex2html -nodoc -nobibsource -unicode --quiet -o - citations.bib  | sed "s/<\/table><hr><p><em>This file was generated by/<\/table>/" | head -n -1 > $(ONTOLOGY)-citations.html
roman: roman.
	rapper roman.owl > /dev/null
organization.html: organization.owl organization-template.html	
	rapper -o dot organization.owl > organization.dot
#	dot -Tpng -o organization.png organization.dot
	./count_linkages.sh organization.owl > organization.links
	sed -e '/<!-- ontology links -->/r organization.links' organization-template.html > organization-skel.html
	specgen2.py organization.owl organization organization-skel.html organization-raw.html -i
	grep "<h[1-5] " organization-raw.html | grep -v "mymw-doctype" | grep -v "title" | grep -v "subtitle" | grep -v "abstract" | grep -v "status" | grep -v "contents" | grep -v "subtitle" |  sed 's/\(<h[1-5] \)\(id=.\(\(.*\)\)"\)/<li><a href="#\3"/g'  |  sed 's/\(<\/h[1-5]\)/\1><\/a><\/li/g'   > organization.toc	
#	|sed 's/\(<h\([1-5]\) \)\(id=.\(\(.*\)\)"\)/<li><a href="#\4"><tab indent="\2"/g' |  sed 's/\(<\/h[1-5]\)/\1><\/a><\/li>/g'   > organization.toc	
#	sed 's/\(<h[1-5] \)\(id=.\(\(.*\)\)"\)/<a href="#\3">\1/g'
	sed -e '/<!-- document toc goes here -->/r organization.toc' organization-raw.html > organization.html 
	cp organization.owl ~/public_html/.
	cp organization.html ~/public_html/.
	cp organization.png ~/public_html/.
	cp org_chart_icon.png ~/public_html/.
	cp -f Army-officer-icon.png /var/www/rdf.muninn-project.org/ontologies/.
clean:
	rm -f *~
	